### ISSUE TITLE
How can i get timestamp_micros

### ISSUE THREAD

**Issue by hengfeiyang** [pydantic/speedate#26]
How can i get timestamp_micros like:

https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.timestamp_micros

we need small unit for timestamp.

**Comment by samuelcolvin** [comment]
What's wrong with:

```rs
dt.timestamp() * 1_000_000 * dt.time.microsecond
```

(or `timestamp_tz`)

???

I haven't tried that, just reading the docs and making a guess.

**Comment by samuelcolvin** [comment]
See https://docs.rs/speedate/latest/speedate/struct.DateTime.html#method.timestamp

**Comment by hengfeiyang** [comment]
Maybe we can add a method `timestamp_micros`, so we do need to do it like:

```
dt.timestamp() * 1_000_000 * dt.time.microsecond
```

**Comment by samuelcolvin** [comment]
I don't think that's necessary, it's not very complicated, and we'd need two for `timestamp` and `timestamp_tz`.
