### ISSUE TITLE
[bug] Time serialization does not work with ZoneInfo

### ISSUE THREAD

**Issue by 07pepa** [pydantic/speedate#62]
additional package instaled https://pypi.org/project/tzdata/

since i encountered this while implementing a mirror image your serialization of time for beanie  in python
there is issue when zone info can't get you precise time delta without some date time  (because of DST)

i know this is pydantic... but  what causes error is in speed date
```python
    from pydantic import BaseModel
    from datetime import time
    from zoneinfo import ZoneInfo
    class TimeTest(BaseModel):
        t: time


    assert (TimeTest(t=time(12, 4, 5, 123456, tzinfo=ZoneInfo("America/Fortaleza")))
            .model_dump(mode="json")) != (TimeTest(t=time(12, 4, 5, 123456, tzinfo=ZoneInfo("Europe/Prague")))
                                          .model_dump(mode="json")) 
```

**Comment by 07pepa** [comment]
basicly i confirmed it https://github.com/python/cpython/issues/117598

**Comment by 07pepa** [comment]
this is my own implementation in python (not speedy but may serve as starting point) https://github.com/roman-right/beanie/pull/912

**Comment by davidhewitt** [comment]
Thanks, I think this is probably an issue in `pydantic-core`, so for now I've reopened in the top level project at https://github.com/pydantic/pydantic/issues/9571
